# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57502d156a937d6ebbe1df65b89cb9cce7f7967ec05103b43076e2315f7836fc097721483d6143adcb418f93e4f5f155d2cbe5f60def587553af34e7275d8a45

test:
  secret_key_base: 24518c9241ad6a7dde1c91f9d70c2f3a691eb75093e91fe42b7dfc13126896d164abb5b94c8efcc3f9d6ce721035ec6b3887077398b2f1d517fa6d152f1d55d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
